### ISSUE TITLE
script #3 EDA script w/ command line arguments

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/DSCI522_309#24]

**Comment by marvinmin** [comment]
![image](https://user-images.githubusercontent.com/55464330/73044761-f1365700-3e1f-11ea-8cf0-c7aab0984794.png)
The plot for correlation I got is too ugly, do you guys have any better idea to make it nicer?

**Comment by marvinmin** [comment]
![image](https://user-images.githubusercontent.com/55464330/73045387-8d615d80-3e22-11ea-9e55-b2ced1619b38.png)

I guess this one is better. Used only numerical variables instead.
