### ISSUE TITLE
Good documentation script - minor documentation suggestions

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_309#33]
- You should note in your documentation that the Revenue column is dropped - this causes the script to fail if there is no Revenue column in the url specified.
- Documentation could be more clear regarding activity of path - if the person using it is distracted or has been marking for a while they might specify something like `data/test.csv` and end up with an extra `test.csv` folder. ^_^ To be extra clear indicate "stored in the data folder specified by argument localpath" and then under local path perhaps use "Local file path to folder in which data csvs will be written".
- Good job including a default url!
- Good test, fails as expected!

**Comment by marvinmin** [comment]
Thank you for the suggestions. Modified the documentation of the scripts based on them.
