### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/DSCI522_309#5]

**Comment by aromatic-toast** [comment]
isn't it preferable to have the .Rmd EDA document rendered as a .md so that you can see it on Github?

**Comment by marvinmin** [comment]
> isn't it preferable to have the .Rmd EDA document rendered as a .md so that you can see it on Github?

yes, you are right, we will add the md file when we finish the final EDA

**Comment by vermashivam679** [comment]
My mistake.. I made the html file because I could see the plotly interactive plots... but the github shows the rawfile. I will change that to .md

**Comment by marvinmin** [comment]
For the last plot in EDA, I think we may need to change the order of the x_axis. I'll look into it.

**Comment by aromatic-toast** [comment]
may want to add titles to the histograms shown near the top of the .md. Not completely clear what these plots are showing.

**Comment by marvinmin** [comment]
> may want to add titles to the histograms shown near the top of the .md. Not completely clear what these plots are showing.

which histograms? the one with two features facet?

**Comment by vermashivam679** [comment]
Hey guys, I reviewed everything & it seems fine to me.... There is just one thing that we should have changed in the graph...showing relative frequency in barplots instead of count, the image shows how I wanted it to show but couldn't figure out how in ggplot. 
 

![image (1)](https://user-images.githubusercontent.com/54871245/72689067-3fff8c00-3ac2-11ea-9ff1-fd0c5213c302.png)

**Comment by marvinmin** [comment]
> > may want to add titles to the histograms shown near the top of the .md. Not completely clear what these plots are showing.
> 
> which histograms? the one with two features facet?

added title for this histogram

**Comment by marvinmin** [comment]
> Hey guys, I reviewed everything & it seems fine to me.... There is just one thing that we should have changed in the graph...showing relative frequency in barplots instead of count, the image shows how I wanted it to show but couldn't figure out how in ggplot.
> 
> ![image (1)](https://user-images.githubusercontent.com/54871245/72689067-3fff8c00-3ac2-11ea-9ff1-fd0c5213c302.png)

How did you calculate the frequency? Is it the total number of trues in a month divided by the total number of trues? or divided by the total number of counts for both trues and falses?
