### ISSUE TITLE
Action Items for Shivam

### ISSUE THREAD

**Issue by vermashivam679** [UBC-MDS/DSCI522_309#64]
- Represent the units for the numeric variables in the EDA, try out changing it to log scale to better show skewness. 
- Improve the project summary and the report.

**Comment by marvinmin** [comment]
firas suggested to just cut off the tails and make it clear we cut the tail off.

**Comment by marvinmin** [comment]
also, we need some tests in the modeling.py script, and you can refer to the tests in pre_process.py

**Comment by vermashivam679** [comment]
> firas suggested to just cut off the tails and make it clear we cut the tail off.

We can't cut off the tails because for many variables most of the values are 0 hence making non-zero values as outliers. WIll try log scale instead
